llanguage: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "TPnoInUiVuLmNsGO+nPVMQneod5kIwU1t4lQgh5+PM+2aNFCL64iCCLuYUDAb3/1OaZWCfqaxwCcFV372JYymtrch4Qi3i6iFzy3vNkFGRgE4RmGFUkvy8QjvzGmQa0Qa/yQl+OdJF2qI3rJ4QeQZcqhBRDVR1S4IGDncumjyheAthI5GTvVD7KClLttF6R1MygFB0hM7rU534rOOb8edcPh5TvqHV+AUcpM1JzhRdJpOi4W7UFAsKOV52HZEu8I86NUhbBNg2fb7uGhxh2Le/ttdugIC9acj7dSi3bQuj8PYkjvx893gg1cHsAT1HP+4aH13XmjmtF/aAsJsywx66DYfUa5v3z8djwQjwnk6xqGvzhh/qhH02WLnE0Hyg1sJJgesiR2bqBM1jS14QZ/zdhQuP2vtCQJkJZwhbZmZwHUHIAdSt3CDMXo482GReCfPHe/RBqtfVND2BvEmDyhHB7Mz2rNJ5aKrNeq1F18h42ygo7dIsBpNGpML5MSl6r59rQZwOmHCMGdSZL3VJUV+jyWMIjzl4VDjl32dWmOwezMzpyxv1nqMRr4rl+UhGd9nPZ45wlULIX4oxMpr4bGulTMcc7W4ioqnc8ybinf6lNxh4tTuLm8g1R2R0s8rzALp8aXuUxTqIRITbhLgZzqcZzlknvZjY87pdTc+kd8KC8="
