language: node_js
node_js:
  - "node"

branches:
  only:
    - master

script:
  - npm run build
  - npm install -g firebase-tools

after_success:
  - firebase use --token $FIREBASE_TOKEN production
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
